name: intent
description: A simple to use Flutter plugin to deal with Android Intents - your one-stop-solution for Android Intents.
version: 1.4.0
homepage: https://github.com/itzmeanjan/intent

environment:
  sdk: '>=3.0.0 <4.0.0'
  
dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: io.github.itzmeanjan.intent
        pluginClass: IntentPlugin
